package com.ca.directory;
// automatically generated by ant build.xml file.
//THIS FILE MUST NOT BE ADDED TO svn OR THE LIVE MAKE SYSTEM

public class BuildNumber {

    public static String value = "JXplorer (build JXv3.3.1.2 2023-04-12 15:52 MST)";

}
        